### ISSUE TITLE
[TRACKING ISSUE] kde: minor performance, feature, and style modifications

### ISSUE THREAD

**Issue by trueNAHO** [danth/stylix#306]
# About

This is a tracking issue for minor [`kde`](https://github.com/danth/stylix/blob/53d3e5d5b36a5227b906e00d7e884dcfb7852403/modules/kde/hm.nix) source code improvements.

This tracking issue should simplify the incoming merge conflict resolution.

# Steps

- [ ] https://github.com/danth/stylix/pull/303
- [ ] https://github.com/danth/stylix/pull/304
- [ ] https://github.com/danth/stylix/pull/305

# Unresolved Questions

- [ ] Should we [rollup](https://forge.rust-lang.org/release/rollups.html) the [individual PRs](#steps)?

**Comment by danth** [comment]
Feel free to go ahead and merge the approved PRs in the correct order.

A rollup would clean up the commit history a little, but I wouldn't say it's strictly necessary.
