### ISSUE TITLE
treewide: optionalize wallpaper functionality

### ISSUE THREAD

**Issue by trueNAHO** [danth/stylix#442]
# About

This is a tracking issue for optionalizing wallpaper functionality, when supported.

# Steps

- [x] https://github.com/danth/stylix/issues/200
- [ ] `treewide: add 'options.stylix.targets.<TARGET>.wallpaper' options`
  - hyprland
  - kde
  - [ ] Where else are wallpapers enforced?

# Unresolved Questions

- [ ] How to optionalize the wallpaper functionality?

**Comment by danth** [comment]
So, an option like `enableWallpaper` under each target?

**Comment by trueNAHO** [comment]
> So, an option like `enableWallpaper` under each target?

Yes, I had the same idea. However, I would simplify the option name to `wallpaper`.

For consistency, we could implement and use a helper function with an appropriate `description`, similar to `mkEnableTarget`:

```nix
options.stylix.targets.hyprland = let
  target = "Hyprland";
in {
  enable = lib.stylix.mkEnableTarget target true;
  wallpaper = lib.stylix.mkEnableWallpaper target false;
}
```

**Comment by NovaViper** [comment]
Hey @trueNAHO would this be an option that can be set globally for stylix? I actually want to disable stylix's wallpaper functionality in favor of plasma-manager's wallpaper module as that module lets me set multiple wallpapers for KDE Plasma.

**Comment by compactcode** [comment]
This is my current thinking which depends on https://github.com/danth/stylix/issues/200

- If `sylix.image` is set (currently mandatory) then we configure all `enabled` wallpaper services.
  - It shouldn't be the responsibility of sylix to decide (and maintain code for) which wallpaper service should be used.
- If `sylix.image` is not set then we do not configure any wallpaper services.
  - If the user doesn't want wallpaper then this is the way.
  - If the user wants to do something custom (e.g. a folder with rotating images) with wallpaper they now have unobstructed control to configure their chosen service.

**Comment by trueNAHO** [comment]
> would this be an option that can be set globally for stylix?

The `options.stylix.targets.<TARGET>.wallpaper` options would be `<TARGET>` specific, similar to `options.stylix.targets.<TARGET>.enable`.

Based on the following use cases, it makes sense to add a `stylix.enableWallpaper` option complementary to `stylix.autoEnable`:

- Get color scheme from `stylix.image` without setting `stylix.image` as wallpaper: `stylix = { enableWallpaper = false; image = image; }`.

- Get color scheme from `stylix.image` and set `stylix.image` as wallpaper: `stylix = { enableWallpaper = true; image = image; }`.

- Manually declare color scheme (`stylix.base16Scheme`) and entirely ignore `stylix.image`: `stylix = { base16Scheme = base16Scheme; enableWallpaper = false; image = null; }`.

For reference, [it has been considered to better rename the `stylix.autoEnable` option](https://github.com/danth/stylix/pull/244#issuecomment-2156716903). Additionally, these use cases somewhat correspond to the [slideshow feature suggestion](https://github.com/danth/stylix/issues/63).

> I actually want to disable stylix's wallpaper functionality in favor of plasma-manager's wallpaper module as that module lets me set multiple wallpapers for KDE Plasma.

My previously mentioned use cases and an additional `options.stylix.targets.kde.allpaper` would resolve this scenario. For reference, I added the `kde` module to the [`Steps`](https://github.com/danth/stylix/issues/442#issue-2361824933) required to resolve this tracking issue.

> This is my current thinking which depends on #200
>
> * If `sylix.image` is set (currently mandatory) then we configure all `enabled` wallpaper services.
>   * It shouldn't be the responsibility of sylix to decide (and maintain code for) which wallpaper service should be used.
> * If `sylix.image` is not set then we do not configure any wallpaper services.
>   * If the user doesn't want wallpaper then this is the way.
>   * If the user wants to do something custom (e.g. a folder with rotating images) they now have unobstructed control to configure their chosen service.

This corresponds to my previously mentioned use cases, except that `stylix.enableWallpaper` provides a default implementation for setting wallpapers:

>   * It shouldn't be the responsibility of sylix to decide (and maintain code for) which wallpaper service should be used.

Considering that the scope of wallpaper optionality is larger than initially anticipated, it might be better to extend the scope of this tracking issue. Consequently, the https://github.com/danth/stylix/issues/200 issue is included, and the following statement is removed from the top-level description:

> Unlike https://github.com/danth/stylix/issues/200, this does not optionalize the `stylix.image` declaration. Instead, it should be possible to disable wallpapers being set, when supported.
